config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root 'home#index'
  resources :home

  devise_for :users
  
  resources :sports

  resources :employees
  
  resources :companies

  resources :students
  resources :teachers

  resources :subscriptions do
    get :pay_now, on: :collection
  end
  resources :subscription_plans

  resources :categories
  resources :products

  resources :articles do
    resources :comments
  end
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  namespace :api do
    namespace :v1 do
      resources :users, only: [:index, :show]
      resources :products
    end
  end
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/article.rb
class Article < ApplicationRecord
	has_many :comments, inverse_of: :article, dependent: :destroy
  
  accepts_nested_attributes_for :comments, allow_destroy: true, reject_if: :all_blank

  validates :title, presence: true
  validates :body, presence: true, length: { minimum: 10 }
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products, dependent: :destroy
  validates :name, presence: true, uniqueness: true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
  validates :commenter, presence: true
  validates :body, presence: true
end

app/models/company.rb
class Company < ApplicationRecord
  has_many :pictures, as: :imageable
  accepts_nested_attributes_for :pictures, allow_destroy: true, reject_if: :all_blank
  validates :name, presence: true, uniqueness: true
end

app/models/employee.rb
class Employee < ApplicationRecord
  has_many :pictures, as: :imageable
  accepts_nested_attributes_for :pictures, allow_destroy: true, reject_if: :all_blank
  validates :name, uniqueness: true
  validate :employee_details

  private
    def employee_details
      if name == ""
        errors.add(:name,"field is empty")
      end
    end
end

app/models/picture.rb
class Picture < ApplicationRecord
  belongs_to :imageable, polymorphic: true
  has_one_attached :attachment 
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
  validates :name, presence: true, uniqueness: true
  
end

app/models/sport.rb
class Sport < ApplicationRecord
	validates :name, presence: true, uniqueness: true
end

app/models/student.rb
class Student < ApplicationRecord
  has_and_belongs_to_many :teachers
  validates :name, presence: true, uniqueness: true
  validates :age, presence: true
end

app/models/subscription.rb
class Subscription < ApplicationRecord
  belongs_to :user
  belongs_to :subscription_plan
end

app/models/teacher.rb
class Teacher < ApplicationRecord
  has_and_belongs_to_many :students
  validates :name, presence: true, uniqueness: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :subscriptions, dependent: :destroy
  has_many :subscription_plans, through: :subscriptions
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  before_action :authenticate_user!
  def index
    @subscriptions = Subscription.all
  end

  def new
    @subscription = Subscription.new
  end

  def show
    @subscription = Subscription.find(params[:id])
  end

  def create
    @subscription = Subscription.new(subscription_params)
    if Razorpay::Utility.verify_payment_signature(verify_signature)
      @subscription.save
      byebug
      @subscriptionas = Razorpay::Subscription.create plan_id: @subscription.subscription_plan.razorpay_plan_id, customer_id: current_user.customer_id, start_at: (Time.now + (60 * 60 * 24)).to_i, total_count: 3

      SubscriptionMailer.with(subscription: @subscription).new_subscription_email.deliver_later
      redirect_to subscriptions_path
    else
      redirect_to pay_now_subscriptions_path
    end
  end

  def pay_now
    @subscription = Subscription.new
    @subscription_plan = SubscriptionPlan.find_by_id(params[:subscription_plan][:id])
    @order = Razorpay::Order.create amount: (@subscription_plan.plan_value * 100).to_i, currency: 'INR', receipt: 'TEST'
    if current_user.customer_id.blank?
      @customer = Razorpay::Customer.create name: current_user.name, email: current_user.email, contact: current_user.contact_no,fail_existing: '0'
      current_user.update(customer_id: @customer.id)
    end
  end

  private
    def subscription_params
      params.require(:subscription).permit(:name, :subscription_plan_id, :user_id, :razorpay_payment_id, :razorpay_order_id, :razorpay_signature)
    end

    def verify_signature
      { 
      :razorpay_order_id   => @subscription.razorpay_order_id, 
      :razorpay_payment_id => @subscription.razorpay_payment_id, 
      :razorpay_signature  => @subscription.razorpay_signature 
      }
    end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sports_helper.rb
module SportsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/subscriptions/index.html.erb
<div class="row">
  
  
  <div class="col">
    <h3>Your's Subscription's </h3>
    <table class="table  table-hover">
      <tr class="table-dark">
        <th>SNo.</th>
        <th>Plan Name</th>
        <th>Plan Type</th>
        <th>Plan Value</th>
        <th>Option</th>
      </tr>
      <% count = 1 %>
      <% @subscriptions.each do |subscription| %>
        <tr class="table-primary">

          <td><%= count %></td>
          <td><%= subscription.subscription_plan.plan_name %></td>
          <td><%=  subscription.subscription_plan.plan_type %></td>
          <td><%=  subscription.subscription_plan.plan_value %></td>
          <td><%= link_to "View",subscription_path(subscription),class: 'link-success' %></td>
          <% count += 1 %>
        </tr>
      <% end %>
    </table>
    <%= link_to 'Take New Subscription', new_subscription_path %><br>
    <%= link_to "Back", root_path %>
  </div>
 
</div>

app/views/subscriptions/new.html.erb
<div class="row">
  <div class="col-4"></div>
  <div class="col-4">
    <h2>Choose Plan</h2>
    <%= form_tag pay_now_subscriptions_path, method: 'get' do %>
      
      <% subscription_plan_options.each do |plan| %>
        <%= radio_button("subscription_plan", "id", plan.id, checked: true) %> <b><%= plan.plan_name %></b> - <%=plan.plan_value %>(<i><%= plan.plan_type%></i>)<br>
      <% end %>
      <%= submit_tag 'Proceed to payment', class: 'btn btn-info' %>
    <% end %>
  </div>
</div>

app/views/subscriptions/pay_now.html.erb
<div class="row">
  <div class="col-4"></div>
  <div class="col-4">
    <h2>Orders Details</h2>
    <strong>Plan Name : </strong><%= @subscription_plan.plan_name %><br>
    <strong>Plan Price : </strong><%= @subscription_plan.plan_value %><br> 
    <strong>Plan Type : </strong><%= @subscription_plan.plan_type %><br>
        

    <%= hidden_field_tag :secret_key, ENV['RAZORPAY_KEY'] %>
    <%= hidden_field_tag :plan_value, @subscription_plan.plan_value.to_i * 100 %>
    <%= form_with model: @subscription, url: subscriptions_path, id: 'subscription-form' do |form| %>
      <%= hidden_field(:subscription, :subscription_plan_id, :value => @subscription_plan.id) %>
      <%= hidden_field(:subscription, :razorpay_payment_id, :value => '') %>
      <%= hidden_field(:subscription, :razorpay_order_id, :value => '') %>
      <%= hidden_field(:subscription, :razorpay_signature, :value => '') %>
      <%= hidden_field(:subscription, :user_id, :value => current_user.id ) %>
    <% end %>
    <button id="rzp-button1" class="btn btn-info">Pay Now</button>
    <script src="https://checkout.razorpay.com/v1/checkout.js"></script>
    <script>
      var options = {
          "key": document.getElementById('secret_key').value,
          "amount": document.getElementById('plan_value').value,
          "currency": "INR",
          "name": "Witmates Pvt. Ltd.",
          "description": "Test Transaction",
          "order_id": "<%= @order.id %>",
          "customer_id": "<%= current_user.customer_id %>",
          "image": "https://media-exp1.licdn.com/dms/image/C510BAQFtTsL2o3MGvg/company-logo_200_200/0/1521272084156?e=2159024400&v=beta&t=EgsCSxu338QQPsOyW_Ey8dgYEj7IVTAMrsNXq8M6PmI",
          "handler": function (response){
              console.log(response);
              document.getElementById('subscription_razorpay_payment_id').value = response.razorpay_payment_id;
              document.getElementById('subscription_razorpay_order_id').value = response.razorpay_order_id;
              document.getElementById('subscription_razorpay_signature').value = response.razorpay_signature;
              document.getElementById("subscription-form").submit();
          },
          "prefill": {
              "name": "<%= current_user.name %>",
              "email": "<%= current_user.email %>",
              "contact": "<%= current_user.contact_no %>",
          },
          "notes": {
              "address": "Razorpay Corporate Office"
          },
          "theme": {
              "color": "#3399cc"
          }
      };
      var rzp1 = new Razorpay(options);
      rzp1.on('payment.failed', function (response){
              alert("Payment Failed");
      });
      document.getElementById('rzp-button1').onclick = function(e){
          rzp1.open();
          e.preventDefault();
      }
    </script>
  </div>
</div>

app/views/subscriptions/show.html.erb
<%#= Razorpay::Order.fetch(@order.id)%>