config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root 'home#index'
  resources :home

  devise_for :users
  
  resources :sports

  resources :employees
  
  resources :companies

  resources :students
  resources :teachers

  resources :subscriptions do
    get :pay_now, on: :collection
  end
  resources :subscription_plans

  resources :categories
  resources :products

  resources :articles do
    resources :comments
  end
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  namespace :api do
    namespace :v1 do
      resources :users, only: [:index, :show]
      resources :products
    end
  end
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/article.rb
class Article < ApplicationRecord
	has_many :comments, inverse_of: :article, dependent: :destroy
  
  accepts_nested_attributes_for :comments, allow_destroy: true, reject_if: :all_blank

  validates :title, presence: true
  validates :body, presence: true, length: { minimum: 10 }
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products, dependent: :destroy
  validates :name, presence: true, uniqueness: true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
  validates :commenter, presence: true
  validates :body, presence: true
end

app/models/company.rb
class Company < ApplicationRecord
  has_many :pictures, as: :imageable
  accepts_nested_attributes_for :pictures, allow_destroy: true, reject_if: :all_blank
  validates :name, presence: true, uniqueness: true
end

app/models/employee.rb
class Employee < ApplicationRecord
  has_many :pictures, as: :imageable
  accepts_nested_attributes_for :pictures, allow_destroy: true, reject_if: :all_blank
  validates :name, uniqueness: true
  validate :employee_details

  private
    def employee_details
      if name == ""
        errors.add(:name,"field is empty")
      end
    end
end

app/models/picture.rb
class Picture < ApplicationRecord
  belongs_to :imageable, polymorphic: true
  has_one_attached :attachment 
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
  validates :name, presence: true, uniqueness: true
  
end

app/models/sport.rb
class Sport < ApplicationRecord
	validates :name, presence: true, uniqueness: true
end

app/models/student.rb
class Student < ApplicationRecord
  has_and_belongs_to_many :teachers
  validates :name, presence: true, uniqueness: true
  validates :age, presence: true
end

app/models/students_teacher.rb
class StudentsTeacher < ApplicationRecord
  belongs_to :teacher
  belongs_to :student
end

app/models/subscription.rb
class Subscription < ApplicationRecord
  belongs_to :user
  belongs_to :subscription_plan
end

app/models/teacher.rb
class Teacher < ApplicationRecord
  has_and_belongs_to_many :students
  validates :name, presence: true, uniqueness: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :subscriptions, dependent: :destroy
  has_many :subscription_plans, through: :subscriptions
end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  before_action :authenticate_user!
  def index
    @teachers = Teacher.all
  end

  def new
    @teacher = Teacher.new
  end

  def show
    @teacher = Teacher.find(params[:id])
  end

  def create
    @teacher = Teacher.new(teacher_params)
    if @teacher.save
      redirect_to teachers_path
    else
      render :new
    end
  end

  def destroy
    @teacher = Teacher.find(params[:id])
    @teacher.destroy

    redirect_to teachers_path
  end

  def edit
    @teacher = Teacher.find(params[:id])
  end

  def update
    @teacher = Teacher.find(params[:id])
    teacher_params[:student_ids].compact_blank.each do |student_id|
      next if @teacher.student_ids.include?(student_id.to_i)
      student = Student.find(student_id)
      @teacher.students << student
    end
    redirect_to teacher_path(@teacher)
  end

  private
    def teacher_params
      params.require(:teacher).permit(:name, student_ids: [])
    end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sports_helper.rb
module SportsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/teachers/edit.html.erb
<div class="row">
  <div class="col-4"></div>
  <div class="col-4">
    <h2>Add New Teacher</h2>
    <%= form_with model: @teacher do |form| %>
      
      <div class="form-group">
        <%= form.label :teacher_name,class: "form-label" %><br>
        <%= form.text_field :name, class: 'form-control',:readonly => true %>
      </div>

      <div class="form-group">
        <%= form.label :Student_name, class: 'form-label' %>
        <%= form.select(:student_ids, Student.all.collect {|s| [ s.name, s.id ] }, 
                                           { :prompt => "Please select"}, 
                                           { :multiple => true, class: 'form-control' }) %>
      </div>
      <br>
      <div class="actions">
        <%= form.submit class: 'btn btn-dark'%>
      </div>
    <% end %>
    <%= link_to "Back",teacher_path(@teacher) %>
  </div>
  <div class="col-4"></div>
</div>

app/views/teachers/index.html.erb
<div class="row">
  <div class="col-4">
    <h2>Registered Teachers</h2>
    <ul>
      <% @teachers.each do |teacher| %>
          <li>
            <%= link_to teacher.name, teacher %>
          </li>
      <% end %>
    </ul>
    <%= link_to "Add New Teacher",new_teacher_path %><br>
    <%= link_to "Back",root_path %>
  </div>
  <div class="col-4"></div>
  <div class="col-4"></div>
</div>

app/views/teachers/new.html.erb
<div class="row">
  <div class="col-4"></div>
  <div class="col-4">
    <h2>Add New Teacher</h2>
    <%= form_with model: @teacher, url: teachers_path do |form| %>
      
      <div class="form-group">
        <%= form.label :teacher_name,class: "form-label" %><br>
        <%= form.text_field :name, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= form.label :Student_name, class: 'form-label' %>
        <%= form.select(:student_ids, Student.all.collect {|s| [ s.name, s.id ] }, { :prompt => "Please select"}, { :multiple => true, class: 'form-control' }) %>
      </div>

      <br>
      <div class="actions">
        <%= form.submit class: 'btn btn-dark'%>
      </div>
    <% end %>
    <%= link_to "Back",teachers_path %>
  </div>
  <div class="col-4"></div>
  
</div>

app/views/teachers/show.html.erb
<div class="row">
  <div class="col-4">
    <h4>Teacher: <i style="color: blueviolet;"><%= @teacher.name %></i></h4>
    <strong style="color: darkblue;"><%= @teacher.name %>'s Students:</strong><br>
    <ul>
      <% @teacher.students.each do |student|  %>
      <li>
        <%= student.name %>  
      </li>
      <% end %>
    </ul>
    <br>
    <%= link_to "Update Students's",edit_teacher_path(@teacher) %><br>
    <%= link_to "Destroy", teacher_path(@teacher),
                      method: :delete,
                      data: { confirm: "Are you sure?" } %><br>
    <%= link_to "Back", teachers_path %>
  </div>
  <div class="col-4"></div>
  <div class="col-4"></div>
</div>