config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root 'home#index'
  resources :home

  devise_for :users
  
  resources :sports

  resources :employees
  
  resources :companies

  resources :students
  resources :teachers

  resources :subscriptions do
    get :pay_now, on: :collection
  end
  resources :subscription_plans

  resources :categories
  resources :products

  resources :articles do
    resources :comments
  end
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  namespace :api do
    namespace :v1 do
      resources :users, only: [:index, :show]
      resources :products
    end
  end
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/article.rb
class Article < ApplicationRecord
	has_many :comments, inverse_of: :article, dependent: :destroy
  
  accepts_nested_attributes_for :comments, allow_destroy: true, reject_if: :all_blank

  validates :title, presence: true
  validates :body, presence: true, length: { minimum: 10 }
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products, dependent: :destroy
  validates :name, presence: true, uniqueness: true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
  validates :commenter, presence: true
  validates :body, presence: true
end

app/models/company.rb
class Company < ApplicationRecord
  has_many :pictures, as: :imageable
  accepts_nested_attributes_for :pictures, allow_destroy: true, reject_if: :all_blank
  validates :name, presence: true, uniqueness: true
end

app/models/employee.rb
class Employee < ApplicationRecord
  has_many :pictures, as: :imageable
  accepts_nested_attributes_for :pictures, allow_destroy: true, reject_if: :all_blank
  validates :name, uniqueness: true
  validate :employee_details

  private
    def employee_details
      if name == ""
        errors.add(:name,"field is empty")
      end
    end
end

app/models/picture.rb
class Picture < ApplicationRecord
  belongs_to :imageable, polymorphic: true
  has_one_attached :attachment 
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
  validates :name, presence: true, uniqueness: true
  
end

app/models/sport.rb
class Sport < ApplicationRecord
	validates :name, presence: true, uniqueness: true
end

app/models/student.rb
class Student < ApplicationRecord
  has_and_belongs_to_many :teachers
  validates :name, presence: true, uniqueness: true
  validates :age, presence: true
end

app/models/subscription.rb
class Subscription < ApplicationRecord
  belongs_to :user
  belongs_to :subscription_plan
end

app/models/teacher.rb
class Teacher < ApplicationRecord
  has_and_belongs_to_many :students
  validates :name, presence: true, uniqueness: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :subscriptions, dependent: :destroy
  has_many :subscription_plans, through: :subscriptions
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!
  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
  end

  def show
    @category = Category.find(params[:id])
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to categories_path
    else
      render :new
    end
  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy

    redirect_to categories_path
  end

  private
    def category_params
      params.require(:category).permit(:name)
    end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sports_helper.rb
module SportsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/categories/edit.html.erb
<h1>Categories#edit</h1>
<p>Find me in app/views/categories/edit.html.erb</p>

app/views/categories/index.html.erb
<div class="row">
  <div class="col-4">
    <h2>Registered Categories</h2>

    <ul>
      <% @categories.each do |category| %>
       
          <li>
            <%= link_to category.name, category %>
          </li>
        
      <% end %>
    </ul>

    <%= link_to "Add New Category",new_category_path %><br>
    <%= link_to "Back", root_path %>
  </div>
  <div class="col-4"></div>
  <div class="col-4"></div>
</div>

app/views/categories/new.html.erb
<div class="row">
  <div class="col-4"></div>
  <div class="col-4">
    <h2>Add New Category</h2>
    <%= form_with model: @category, url: categories_path do |form| %>
      
      <div class="form-group">
        <%= form.label :category_name,class: "form-label" %><br>
        <%= form.text_field :name, class: 'form-control' %>
      </div><br>

      <div class="btn-group" role="group" aria-label="Basic example">
        <%= form.submit  class: 'btn btn-dark' %>
      </div>
    <% end %>
    <%= link_to "Back",categories_path %>
  </div>
  <div class="col-4"></div>
  
</div>

app/views/categories/show.html.erb
<div class="row">
  <div class="col-4">
    <h2>This Category Product</h2>
    <ul>
      <% @category.products.each do |product| %>
        <li>
          <%= product.name%>
        </li>
      <% end %>
    </ul>
    <%= link_to "Destroy", category_path(@category),
                      method: :delete,
                      data: { confirm: "Are you sure?" } %><br>
    <%= link_to "Back", categories_path %>
  </div>
  <div class="col-4"></div>
  <div class="col-4"></div>
</div>